/*****************************************************************************
 *
 *  BLE Mesh Device Composition Data
 *
 *  Autogenerated file, do not edit
 *
 ****************************************************************************/

#include <stddef.h>
#include <stdint.h>

const uint8_t __mesh_dcd[] = {
  0xff, 0x02,   /* Company ID = 0x02ff */
  0xb0, 0xf0,   /* Product ID = 0xf0b0 */
  0x34, 0x12,   /* Version Number = 0x1234 */
  0x20, 0x00,   /* Capacity of Replay Protection List = 0x0020 */
  /*
   * 	Bit Feature Notes
   * 	0	Relay	Relay feature support: 0 = False, 1 = True
   * 	1	Proxy	Proxy feature support: 0 = False, 1 = True
   * 	2	Friend	Friend feature support: 0 = False, 1 = True
   * 	3	Low Power	Low Power feature support: 0 = False, 1 = True
   * 	4–15	RFU	Reserved for Future Use
   */
  0x03, 0x00,   /* Features Bitmask = 0x0003 */
  /* Begin Primary Element */
  0x00, 0x00,       /* Location = 0x0000 */
  0x04,       /* Number of SIG Models = 0x04 */
  0x01,       /* Number of Vendor Models = 0x01 */
  /* Begin SIG Models */
  0x00, 0x00,       /* Primary Conf Server */
  0x01, 0x00,       /* Primary Conf Client */
  0x00, 0x10,       /* Generic On/Off Server = 0x1000*/
  0x01, 0x10,       /* Generic On/Off Client = 0x1001*/
  /* End SIG Models */
  /* Begin Vendor Models */
  0xff, 0x02, 0xcd, 0xab,       /* Vendor Model */
  /* End Vendor Models */
  /* End Primary Element */
};

const size_t __mesh_dcd_len = sizeof(__mesh_dcd);
const uint8_t *__mesh_dcd_ptr = __mesh_dcd;
