/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef GATT_DB_H
#define GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_device_name                      3

typedef enum {
  mesh_provisioning_service      = 0x0001,
  mesh_proxy_service             = 0x0002,
  bg_gattdb_data_all_caps = 0x0003
} bg_gattdb_data_cap_t;

#endif
