/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#include <stdint.h>
#include "bg_gattdb_def.h"

#ifdef __GNUC__
#define GATT_HEADER(F) F __attribute__ ((section(".gatt_header")))
#define GATT_DATA(F) F __attribute__ ((section(".gatt_data")))
#else
#ifdef __ICCARM__
#define GATT_HEADER(F) _Pragma("location=\".gatt_header\"") F
#define GATT_DATA(F) _Pragma("location=\".gatt_data\"") F
#else
#define GATT_HEADER(F) F
#define GATT_DATA(F) F
#endif
#endif

GATT_DATA(const uint16_t bg_gattdb_data_uuidtable_16_map[]) =
{
  0x2800,
  0x2801,
  0x2803,
  0x1800,
  0x2a00,
  0x2a01,
  0x180a,
  0x2a29,
  0x1827,
  0x2adb,
  0x2adc,
  0x1828,
  0x2add,
  0x2ade,
  0x2902,
};

GATT_DATA(const uint8_t bg_gattdb_data_uuidtable_128_map[]) =
{
  0x0   //IAR workaround for empty array
};

GATT_DATA(const struct bg_gattdb_attribute_chrvalue bg_gattdb_data_attribute_field_18) = {
  .properties = 0x10,
  .index = 4,
  .max_len = 0,
  .data = NULL,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len  bg_gattdb_data_attribute_field_17) = {
  .len = 5,
  .data = { 0x10, 0x13, 0x00, 0xde, 0x2a, }
};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue bg_gattdb_data_attribute_field_16) = {
  .properties = 0x04,
  .index = 3,
  .max_len = 0,
  .data = NULL,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len  bg_gattdb_data_attribute_field_15) = {
  .len = 5,
  .data = { 0x04, 0x11, 0x00, 0xdd, 0x2a, }
};
GATT_DATA(const struct bg_gattdb_buffer_with_len  bg_gattdb_data_attribute_field_14) = {
  .len = 2,
  .data = { 0x28, 0x18, }
};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue bg_gattdb_data_attribute_field_12) = {
  .properties = 0x10,
  .index = 2,
  .max_len = 0,
  .data = NULL,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len  bg_gattdb_data_attribute_field_11) = {
  .len = 5,
  .data = { 0x10, 0x0d, 0x00, 0xdc, 0x2a, }
};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue bg_gattdb_data_attribute_field_10) = {
  .properties = 0x04,
  .index = 1,
  .max_len = 0,
  .data = NULL,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len  bg_gattdb_data_attribute_field_9) = {
  .len = 5,
  .data = { 0x04, 0x0b, 0x00, 0xdb, 0x2a, }
};
GATT_DATA(const struct bg_gattdb_buffer_with_len  bg_gattdb_data_attribute_field_8) = {
  .len = 2,
  .data = { 0x27, 0x18, }
};
GATT_DATA(const struct bg_gattdb_buffer_with_len  bg_gattdb_data_attribute_field_7) = {
  .len = 12,
  .data = { 0x53, 0x69, 0x6c, 0x69, 0x63, 0x6f, 0x6e, 0x20, 0x4c, 0x61, 0x62, 0x73, }
};
GATT_DATA(const struct bg_gattdb_buffer_with_len  bg_gattdb_data_attribute_field_6) = {
  .len = 5,
  .data = { 0x02, 0x08, 0x00, 0x29, 0x2a, }
};
GATT_DATA(const struct bg_gattdb_buffer_with_len  bg_gattdb_data_attribute_field_5) = {
  .len = 2,
  .data = { 0x0a, 0x18, }
};
GATT_DATA(const struct bg_gattdb_buffer_with_len  bg_gattdb_data_attribute_field_4) = {
  .len = 2,
  .data = { 0x40, 0x03, }
};
GATT_DATA(const struct bg_gattdb_buffer_with_len  bg_gattdb_data_attribute_field_3) = {
  .len = 5,
  .data = { 0x02, 0x05, 0x00, 0x01, 0x2a, }
};
struct bg_gattdb_buffer_with_len  bg_gattdb_data_attribute_field_2_data = {
  .len = 20,
  .data = { 0x42, 0x6c, 0x75, 0x65, 0x67, 0x65, 0x63, 0x6b, 0x6f, 0x20, 0x4d, 0x65, 0x73, 0x68, 0x20, 0x44, 0x65, 0x6d, 0x6f, 0x20, }
};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue bg_gattdb_data_attribute_field_2) = {
  .properties = 0x02,
  .index = 0,
  .max_len = 20,
  .data_varlen = &bg_gattdb_data_attribute_field_2_data,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len  bg_gattdb_data_attribute_field_1) = {
  .len = 5,
  .data = { 0x02, 0x03, 0x00, 0x00, 0x2a, }
};
GATT_DATA(const struct bg_gattdb_buffer_with_len  bg_gattdb_data_attribute_field_0) = {
  .len = 2,
  .data = { 0x00, 0x18, }
};
GATT_DATA(const struct bg_gattdb_attribute bg_gattdb_data_attributes_map[]) = {
  { .uuid = 0x0000, .permissions = 0x801, .caps = 0x03, .datatype = 0x00, .min_key_size = 0x00, .constdata = &bg_gattdb_data_attribute_field_0 },
  { .uuid = 0x0002, .permissions = 0x801, .caps = 0x03, .datatype = 0x00, .min_key_size = 0x00, .constdata = &bg_gattdb_data_attribute_field_1 },
  { .uuid = 0x0004, .permissions = 0x801, .caps = 0x03, .datatype = 0x02, .min_key_size = 0x00, .dynamicdata = &bg_gattdb_data_attribute_field_2 },
  { .uuid = 0x0002, .permissions = 0x801, .caps = 0x03, .datatype = 0x00, .min_key_size = 0x00, .constdata = &bg_gattdb_data_attribute_field_3 },
  { .uuid = 0x0005, .permissions = 0x801, .caps = 0x03, .datatype = 0x00, .min_key_size = 0x00, .constdata = &bg_gattdb_data_attribute_field_4 },
  { .uuid = 0x0000, .permissions = 0x801, .caps = 0x03, .datatype = 0x00, .min_key_size = 0x00, .constdata = &bg_gattdb_data_attribute_field_5 },
  { .uuid = 0x0002, .permissions = 0x801, .caps = 0x03, .datatype = 0x00, .min_key_size = 0x00, .constdata = &bg_gattdb_data_attribute_field_6 },
  { .uuid = 0x0007, .permissions = 0x801, .caps = 0x03, .datatype = 0x00, .min_key_size = 0x00, .constdata = &bg_gattdb_data_attribute_field_7 },
  { .uuid = 0x0000, .permissions = 0x801, .caps = 0x01, .datatype = 0x00, .min_key_size = 0x00, .constdata = &bg_gattdb_data_attribute_field_8 },
  { .uuid = 0x0002, .permissions = 0x801, .caps = 0x01, .datatype = 0x00, .min_key_size = 0x00, .constdata = &bg_gattdb_data_attribute_field_9 },
  { .uuid = 0x0009, .permissions = 0x804, .caps = 0x01, .datatype = 0x07, .min_key_size = 0x00, .dynamicdata = &bg_gattdb_data_attribute_field_10 },
  { .uuid = 0x0002, .permissions = 0x801, .caps = 0x01, .datatype = 0x00, .min_key_size = 0x00, .constdata = &bg_gattdb_data_attribute_field_11 },
  { .uuid = 0x000a, .permissions = 0x800, .caps = 0x01, .datatype = 0x07, .min_key_size = 0x00, .dynamicdata = &bg_gattdb_data_attribute_field_12 },
  { .uuid = 0x000e, .permissions = 0x807, .caps = 0x01, .datatype = 0x03, .min_key_size = 0x00, .configdata = { .flags = 0x01, .index = 0x02, .clientconfig_index = 0x00 } },
  { .uuid = 0x0000, .permissions = 0x801, .caps = 0x02, .datatype = 0x00, .min_key_size = 0x00, .constdata = &bg_gattdb_data_attribute_field_14 },
  { .uuid = 0x0002, .permissions = 0x801, .caps = 0x02, .datatype = 0x00, .min_key_size = 0x00, .constdata = &bg_gattdb_data_attribute_field_15 },
  { .uuid = 0x000c, .permissions = 0x804, .caps = 0x02, .datatype = 0x07, .min_key_size = 0x00, .dynamicdata = &bg_gattdb_data_attribute_field_16 },
  { .uuid = 0x0002, .permissions = 0x801, .caps = 0x02, .datatype = 0x00, .min_key_size = 0x00, .constdata = &bg_gattdb_data_attribute_field_17 },
  { .uuid = 0x000d, .permissions = 0x800, .caps = 0x02, .datatype = 0x07, .min_key_size = 0x00, .dynamicdata = &bg_gattdb_data_attribute_field_18 },
  { .uuid = 0x000e, .permissions = 0x807, .caps = 0x02, .datatype = 0x03, .min_key_size = 0x00, .configdata = { .flags = 0x01, .index = 0x04, .clientconfig_index = 0x01 } },
};

GATT_DATA(const uint16_t bg_gattdb_data_attributes_dynamic_mapping_map[]) = {
  0x0003,
  0x000b,
  0x000d,
  0x0011,
  0x0013,
};

GATT_DATA(const uint8_t bg_gattdb_data_adv_uuid16_map[]) = { 0x27, 0x18, 0x28, 0x18, };
GATT_DATA(const uint8_t bg_gattdb_data_adv_uuid128_map[]) = { 0x0 };
GATT_HEADER(const struct bg_gattdb_def bg_gattdb_data) = {
  .attributes = bg_gattdb_data_attributes_map,
  .attributes_max = 20,
  .uuidtable_16_size = 15,
  .uuidtable_16 = bg_gattdb_data_uuidtable_16_map,
  .uuidtable_128_size = 0,
  .uuidtable_128 = bg_gattdb_data_uuidtable_128_map,
  .attributes_dynamic_max = 5,
  .attributes_dynamic_mapping = bg_gattdb_data_attributes_dynamic_mapping_map,
  .adv_uuid16 = bg_gattdb_data_adv_uuid16_map,
  .adv_uuid16_num = 2,
  .adv_uuid128 = bg_gattdb_data_adv_uuid128_map,
  .adv_uuid128_num = 0,
  .caps_mask = 0x03,
  .enabled_caps = 0x00,
};

const struct bg_gattdb_def *bg_gattdb = &bg_gattdb_data;
